title: Alerighi's site
description: Alessandro Righi personal website
url: https://alerighi.it
author: Alessandro Righi
excerpt_separator: "<!--more-->"
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
exclude:
  - vendor
plugins:
  - jekyll-feed
