#!/bin/sh
# small utility to install my SSH keys in a system
# just run: curl https://alerighi.it/ssh | bash 

username="alerighi"

if [ $# -eq 2 ]; then
	username=$1
fi

echo "installing SSH keys of GitHub user ${username}"

ssh_dir="${HOME}/.ssh"
keys_file="${ssh_dir}/authorized_keys"
keys_url="https://github.com/${username}.keys"

if ! [ -d "${ssh_dir}" ]; then
	mkdir "${ssh_dir}"
fi

if type curl; then
	curl "${keys_url}" >> "${keys_file}"
elif type wget; then
	wget "${keys_url}" --output-document=- >> "${keys_file}"
else
	echo "error: curl or wget required to run this script"
	exit 1
fi

echo "installed ssh keys"
